# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='empid',
            new_name='employee_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='empname',
            new_name='employee_name',
        ),
    ]
